### ISSUE TITLE
Helm charts improvement

### ISSUE THREAD

**Issue by fabiofilz** [viz-centric/flair-helm-charts#4]
Hi there,

We are planning to deploy the application into Production soon, but we have a pre-req that the application must use sealed secrets instead of declaring the credentials into the values.yaml files.

Would it be possible to:
1 - modify the charts to use secrets and manage those using sealed secrets charts?
2 - create a unique helm charts wrapping the all other helm charts so it can be stored into artifactory as a unique component
3 - authenticate the connection with CRDB using der and pk8 file instead of login/password as the example jdbc:postgresql://cockroachdb.amazonaws.com:26257/DATABASENAME?user=USERNAME&ApplicationName=APPNAME&sslcert=%2Fcerts%2Fpt1%2FFILENAME.der&sslkey=%2Fcerts%2Fpt1%2FFILENAME.pk8&sslmode=require&ssl=true

Kind regards,
Fabio

**Comment by admin-vizcentric** [comment]
Hi @Fabiofilz,

Glad to hear that you are planning to deploy FlairBI into Production and thanks a lot for raising your concerns. Please find below answers to your questions.

1 - modify the charts to use secrets and manage those using sealed secrets charts?
> Yes, I believe this is possible. I will forward this to our dev team. You can expect a reply from them early this week.

2 - create a unique helm charts wrapping the all other helm charts so it can be stored into artifactory as a unique component
> This will be part of our flair-operator release which will potential remove some operational and deployment burden for our customers and users. We are not sure about the timelines for this yet.

3 - authenticate the connection with CRDB using der and pk8 file instead of login/password as the example jdbc:postgresql://cockroachdb.amazonaws.com:26257/DATABASENAME?user=USERNAME&ApplicationName=APPNAME&sslcert=%2Fcerts%2Fpt1%2FFILENAME.der&sslkey=%2Fcerts%2Fpt1%2FFILENAME.pk8&sslmode=require&ssl=true
> Our dev team has been working on a solution for this and is currently in testing. We expect this feature to be out in the next week. However, that would be a minor release. We will let you know once we release it.

Best regards,
Vizcentric team

**Comment by kalyan21** [comment]
Hi @fabiofilz,

This PR: #5 contains the feature enhancements needed for the 1st and 3rd points. 

**Reg Point 1:** We have added secret mount for all services and hence now its possible to mount secrets onto all our services. 

**Reg Point 3:** We have released a snapshot version of flair engine and flair bi which contain the changes needed for you to add ssl config params while creating database connectors. You can find the versions updated in the README.md

These are snapshot version and we plan to release a minor version some time next week along with some more new features. 

Also, when it comes to the 2nd point, we would like to understand what you are planning to achieve and also your pain points. Based on the best practices in the industry we plan to remove the operational burden from any team by baking this functionality into flair-operator. 

Best regards,
Vizcentric Team

**Comment by admin-vizcentric** [comment]
Hi @fabiofilz 

This PR: #5  contains the feature enhancements needed for the 1st and 3rd points. 

**Reg Point 1:** We have added secret mount for all services and hence now its possible to mount secrets onto all our services. 

**Reg Point 3:** We have released a snapshot version of flair engine and flair bi which contain the changes needed for you to add ssl config params while creating database connectors. You can find the versions updated in the README.md

These are snapshot version and we plan to release a minor version some time next week along with some more new features. 

Also, when it comes to the 2nd point, we would like to understand what you are planning to achieve and also your pain points. Based on the best practices in the industry we plan to remove the operational burden from any team by baking this functionality into flair-operator. 

Best regards,
Vizcentric Team

**Comment by fabiofilz** [comment]
Hi Vizcentric team,

Thank you for your prompt response.

I am going to check the 1st and 3rd points.

Regard to the 2nd point we have in place pipelines to deploy any change into any environment so we have a cdci controlling what is being deployed for example docker image version and so on.

In order to keep it more organised we created a helm chart to wrap all service helm charts so we can storage it into artifactory as one object and we can track that this package version was deployed.

Currently it is
- flair-bi/charts/flair-bi
- flair-bi/charts/flair-cache
- flair-bi/charts/flair-couchdb
- flair-bi/charts/flair-engine
- flair-bi/charts/flair-notifications
- flair-bi/charts/flair-registry

Result is 6 packages (flair-bi-0.1.0.tgz,flair-registry-0.1.0.tgz, flair-cache-0.1.0.tgz,flair-couchdb-0.1.0.tgz, flair-engine -0.1.0.tgz and flair-notifications -0.1.0.tgz

And we would like to organise in this way
- flair-bi/flair-deployment/charts

result is 1 packages flair-deployment-0.1.0.tgz with all applications inside it.

So we can execute just one command and it will be deployed without the need to control if the other service was deployed.

helm upgrade \
    --install \
    --wait \
    --namespace flair \
    flair-deployment./flair-deployment


Kind regards,
Fabio

**Comment by fabiofilz** [comment]
Hi Vizcentric team,

I am checking the 1st point and we would like to use SealedSecret to get sensitive information like credentials instead of getting environment variable from the value.yaml as POSTGRES_USER, POSTGRES_PASS, BITBUCKET_USER and BITBUCKET_PASS.

The idea is don't have credentials/sensitive information in BitBucket.

We though it would have something like that

```yaml
--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: flair-deployment
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: flairbi
    spec: 
      containers: 
        - 
          env: 
            - 
              name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: flair-engine-secret
                  key: flairbi_postgres_user
            - 
              name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: flair-engine-secret
                  key: flairbi_postgres_pass
- 
              name: BITBUCKET_USER
              valueFrom:
                secretKeyRef:
                  name: flair-engine-secret
                  key: bitbucket_user
---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: flair-engine-secret
  namespace: flairbi
  creationTimestamp: null
  labels:
    by-k8s-cryptor: "true"
spec:
  flairbi_postgres_user: flairbiadmin
  flairbi_postgres_pass: xyz
  flairengine_postgres_user: flairbiadmin
  flairengine_postgres_pass: qwe
  bitbucket_user: xxxx
  bitbucker_pass: zzzzz
  template:
    metadata:
      labels:
        jenkins.io/credentials-type: usernamePassword
```

As reference: https://medium.com/faun/using-kubernetes-secrets-as-environment-variables-5ea3ef7581ef

Kind regards,
Fabio
